# This is a basic workflow to help you get started with Actions

name: CI-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build Swift package
        run: xcodebuild -showdestinations -scheme Package211

      - name: Build and test ( iOS 15.0)
        run: xcodebuild test -scheme Package211 -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
